# ------------------------------------------------------------------------------
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Jayesh Badwaik <j.badwaik@fz-juelich.de>
# ------------------------------------------------------------------------------

version = 1

[[annotations]]
path = ["test/share/**"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2025 Jayesh Badwaik <j.badwaik@fz-juelich.de>"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = ["docs/**"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2025 Jayesh Badwaik <j.badwaik@fz-juelich.de>"
SPDX-License-Identifier = "Apache-2.0"
